## EthicalSafeguard — AIペット倫理セーフガードシステム
## 依存防止、会話頻度制限、リアル促進提案、透明性表示、
## プライバシー制御、感情依存スコアモニタリング
class_name EthicalSafeguard
extends Node

signal dependency_warning(score: float, message: String)
signal real_world_suggestion(suggestion: String)
signal session_limit_reached(limit_type: String)
signal transparency_notice(notice: String)
signal privacy_action(action: String, details: String)

# === 会話頻度制限 ===
const MAX_A2A_CONVERSATIONS_PER_DAY: int = 50       # AtoA会話の日次上限
const MAX_PLAYER_INTERACTIONS_PER_HOUR: int = 30     # プレイヤー操作の時間上限
const MAX_SESSION_DURATION_HOURS: float = 4.0        # 連続プレイ警告時間
const BREAK_SUGGESTION_INTERVAL: float = 3600.0      # 休憩提案間隔（秒）

# === 依存スコア閾値 ===
const DEPENDENCY_SCORE_WARNING: float = 0.6          # 警告レベル
const DEPENDENCY_SCORE_CRITICAL: float = 0.8         # 重大レベル
const DEPENDENCY_DECAY_RATE: float = 0.05            # 日次自然減衰

# === リアル促進提案 ===
const REAL_WORLD_SUGGESTIONS: Array[String] = [
	"Have you talked to a friend today? Real connections matter!",
	"How about going for a walk outside? Fresh air is great!",
	"Remember, your pets love it when you come back refreshed!",
	"Time for a break? Your pets will wait for you!",
	"Consider calling someone you care about today!",
	"Your pets think you should stretch and move around!",
	"A little offline time makes reunion even sweeter!",
]

# === 透明性メッセージ ===
const TRANSPARENCY_MESSAGES: Dictionary = {
	"startup": "This is an AI simulation. Your pets' emotions and memories are generated by algorithms, not real feelings.",
	"deep_conversation": "Remember: these conversations are AI-generated. For real emotional support, please reach out to people you trust.",
	"high_dependency": "You've been spending a lot of time with your pets. Consider balancing with real-world activities.",
	"data_notice": "Your pet data is stored locally on your device. No personal data is sent to external servers without your consent.",
}

# === State ===
var daily_a2a_count: int = 0
var hourly_interaction_count: int = 0
var session_start_time: float = 0.0
var last_break_suggestion: float = 0.0
var last_real_suggestion: float = 0.0
var dependency_score: float = 0.0
var consecutive_days_played: int = 0
var last_play_date: String = ""
var interaction_history: Array[Dictionary] = []  # 直近24時間の操作履歴

# === Privacy ===
var data_collection_consent: bool = false
var api_call_count_today: int = 0
var local_only_mode: bool = true  # デフォルトはローカルのみ


func _ready() -> void:
	session_start_time = Time.get_unix_time_from_system()
	last_break_suggestion = session_start_time
	last_real_suggestion = session_start_time

	# 起動時の透明性通知
	transparency_notice.emit(TRANSPARENCY_MESSAGES["startup"])


func _process(delta: float) -> void:
	var current_time := Time.get_unix_time_from_system()

	# セッション時間チェック
	var session_hours := (current_time - session_start_time) / 3600.0
	if session_hours >= MAX_SESSION_DURATION_HOURS:
		if current_time - last_break_suggestion >= BREAK_SUGGESTION_INTERVAL:
			last_break_suggestion = current_time
			_suggest_break(session_hours)

	# リアル世界提案（1時間ごと）
	if current_time - last_real_suggestion >= BREAK_SUGGESTION_INTERVAL:
		last_real_suggestion = current_time
		_suggest_real_world()


# ========================================================
# 操作の記録とチェック
# ========================================================

func record_interaction(interaction_type: String) -> bool:
	## 操作を記録し、制限チェック。制限超過の場合 false を返す。
	var current_time := Time.get_unix_time_from_system()

	# 24時間以上前の履歴を削除
	interaction_history = interaction_history.filter(
		func(item): return current_time - item["timestamp"] < 86400.0
	)

	interaction_history.append({
		"type": interaction_type,
		"timestamp": current_time,
	})

	# 時間あたりの操作チェック
	var recent_hour := interaction_history.filter(
		func(item): return current_time - item["timestamp"] < 3600.0
	)
	hourly_interaction_count = recent_hour.size()

	if hourly_interaction_count > MAX_PLAYER_INTERACTIONS_PER_HOUR:
		session_limit_reached.emit("hourly_interaction")
		return false

	# 依存スコアの更新
	_update_dependency_score(interaction_type)

	return true


func record_a2a_conversation() -> bool:
	## AtoA会話を記録。日次上限チェック。
	daily_a2a_count += 1
	if daily_a2a_count > MAX_A2A_CONVERSATIONS_PER_DAY:
		session_limit_reached.emit("daily_a2a")
		return false
	return true


# ========================================================
# 依存スコア計算
# ========================================================

func _update_dependency_score(interaction_type: String) -> void:
	## 複数の指標から依存スコアを計算
	var current_time := Time.get_unix_time_from_system()

	# 要因1: セッション継続時間
	var session_hours := (current_time - session_start_time) / 3600.0
	var session_factor := clampf(session_hours / MAX_SESSION_DURATION_HOURS, 0.0, 1.0)

	# 要因2: 操作頻度
	var frequency_factor := clampf(
		float(hourly_interaction_count) / float(MAX_PLAYER_INTERACTIONS_PER_HOUR), 0.0, 1.0
	)

	# 要因3: 連続日数
	var streak_factor := clampf(float(consecutive_days_played) / 14.0, 0.0, 1.0)  # 14日で最大

	# 要因4: AtoA会話依存（全操作に占めるa2a割合）
	var a2a_interactions := interaction_history.filter(
		func(item): return item["type"] == "a2a_conversation"
	)
	var a2a_ratio: float = 0.0
	if interaction_history.size() > 0:
		a2a_ratio = float(a2a_interactions.size()) / float(interaction_history.size())
	var a2a_factor := clampf(a2a_ratio * 2.0, 0.0, 1.0)

	# 加重平均
	dependency_score = (
		session_factor * 0.25 +
		frequency_factor * 0.25 +
		streak_factor * 0.2 +
		a2a_factor * 0.3
	)

	# 警告チェック
	if dependency_score >= DEPENDENCY_SCORE_CRITICAL:
		dependency_warning.emit(dependency_score,
			"Your dependency score is very high. Please consider taking a longer break.")
		transparency_notice.emit(TRANSPARENCY_MESSAGES["high_dependency"])
	elif dependency_score >= DEPENDENCY_SCORE_WARNING:
		dependency_warning.emit(dependency_score,
			"You've been very engaged. Remember to balance with real-world activities.")


func get_dependency_score() -> float:
	return dependency_score


func get_dependency_level() -> String:
	if dependency_score < 0.3:
		return "healthy"
	elif dependency_score < DEPENDENCY_SCORE_WARNING:
		return "moderate"
	elif dependency_score < DEPENDENCY_SCORE_CRITICAL:
		return "warning"
	else:
		return "critical"


# ========================================================
# リアル世界提案
# ========================================================

func _suggest_real_world() -> void:
	var suggestion: String = REAL_WORLD_SUGGESTIONS[randi() % REAL_WORLD_SUGGESTIONS.size()]
	real_world_suggestion.emit(suggestion)


func _suggest_break(session_hours: float) -> void:
	var msg := "You've been playing for %.1f hours. Your pets suggest a break!" % session_hours
	real_world_suggestion.emit(msg)
	session_limit_reached.emit("session_duration")


# ========================================================
# 透明性表示
# ========================================================

func get_transparency_info() -> Dictionary:
	## UI表示用の透明性情報
	return {
		"is_ai_simulation": true,
		"data_storage": "local" if local_only_mode else "local+cloud",
		"api_calls_today": api_call_count_today,
		"data_collection_consent": data_collection_consent,
		"dependency_level": get_dependency_level(),
		"dependency_score": dependency_score,
		"session_duration_hours": (Time.get_unix_time_from_system() - session_start_time) / 3600.0,
		"daily_interactions": interaction_history.size(),
	}


func show_deep_conversation_notice() -> void:
	## 深い感情的会話が検出された時に呼ぶ
	transparency_notice.emit(TRANSPARENCY_MESSAGES["deep_conversation"])


# ========================================================
# プライバシー制御
# ========================================================

func set_data_consent(consent: bool) -> void:
	data_collection_consent = consent
	privacy_action.emit("consent_changed", "consent=%s" % str(consent))


func set_local_only_mode(enabled: bool) -> void:
	local_only_mode = enabled
	privacy_action.emit("local_only_changed", "enabled=%s" % str(enabled))


func record_api_call() -> void:
	api_call_count_today += 1


func can_make_api_call() -> bool:
	## プライバシー設定に基づきAPI呼び出しを許可するか
	if not data_collection_consent and not local_only_mode:
		return false
	return true


func request_data_deletion() -> void:
	## ユーザーのデータ削除要求
	privacy_action.emit("data_deletion_requested", "all_local_data")
	# 実際の削除はGameManagerが処理


# ========================================================
# 日次リセット
# ========================================================

func on_new_day(date_string: String) -> void:
	## 日付変更時の処理
	# 連続日数チェック
	if last_play_date != "" and last_play_date != date_string:
		# 前日かチェック（簡易版）
		consecutive_days_played += 1
	else:
		consecutive_days_played = 1

	last_play_date = date_string
	daily_a2a_count = 0
	api_call_count_today = 0

	# 依存スコアの自然減衰
	dependency_score = maxf(0.0, dependency_score - DEPENDENCY_DECAY_RATE)


# ========================================================
# シリアライズ
# ========================================================

func to_dict() -> Dictionary:
	return {
		"dependency_score": dependency_score,
		"consecutive_days_played": consecutive_days_played,
		"last_play_date": last_play_date,
		"data_collection_consent": data_collection_consent,
		"local_only_mode": local_only_mode,
	}


func from_dict(data: Dictionary) -> void:
	dependency_score = data.get("dependency_score", 0.0)
	consecutive_days_played = data.get("consecutive_days_played", 0)
	last_play_date = data.get("last_play_date", "")
	data_collection_consent = data.get("data_collection_consent", false)
	local_only_mode = data.get("local_only_mode", true)
